package com.stt.model;

public class User {

    private Byte id1;
    private Integer id2;
    private Integer id3;
    private Integer id4;
    private Long id5;
    private Boolean id6;
    private Long id7;
    private Float id8;
    private String id9;
    private String id10;



    public User(Byte id1, Integer id2, Integer id3, Integer id4, Long id5, Boolean id6, Long id7, Float id8, String id9, String id10) {
        this.id1 = id1;
        this.id2 = id2;
        this.id3 = id3;
        this.id4 = id4;
        this.id5 = id5;
        this.id6 = id6;
        this.id7 = id7;
        this.id8 = id8;
        this.id9 = id9;
        this.id10 = id10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id1
     *
     * @return the value of user.id1
     *
     * @mbggenerated
     */
    public Byte getId1() {
        return id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id1
     *
     * @param id1 the value for user.id1
     *
     * @mbggenerated
     */
    public void setId1(Byte id1) {
        this.id1 = id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id2
     *
     * @return the value of user.id2
     *
     * @mbggenerated
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id2
     *
     * @param id2 the value for user.id2
     *
     * @mbggenerated
     */
    public void setId2(Integer id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id3
     *
     * @return the value of user.id3
     *
     * @mbggenerated
     */
    public Integer getId3() {
        return id3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id3
     *
     * @param id3 the value for user.id3
     *
     * @mbggenerated
     */
    public void setId3(Integer id3) {
        this.id3 = id3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id4
     *
     * @return the value of user.id4
     *
     * @mbggenerated
     */
    public Integer getId4() {
        return id4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id4
     *
     * @param id4 the value for user.id4
     *
     * @mbggenerated
     */
    public void setId4(Integer id4) {
        this.id4 = id4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id5
     *
     * @return the value of user.id5
     *
     * @mbggenerated
     */
    public Long getId5() {
        return id5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id5
     *
     * @param id5 the value for user.id5
     *
     * @mbggenerated
     */
    public void setId5(Long id5) {
        this.id5 = id5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id6
     *
     * @return the value of user.id6
     *
     * @mbggenerated
     */
    public Boolean getId6() {
        return id6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id6
     *
     * @param id6 the value for user.id6
     *
     * @mbggenerated
     */
    public void setId6(Boolean id6) {
        this.id6 = id6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id7
     *
     * @return the value of user.id7
     *
     * @mbggenerated
     */
    public Long getId7() {
        return id7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id7
     *
     * @param id7 the value for user.id7
     *
     * @mbggenerated
     */
    public void setId7(Long id7) {
        this.id7 = id7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id8
     *
     * @return the value of user.id8
     *
     * @mbggenerated
     */
    public Float getId8() {
        return id8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id8
     *
     * @param id8 the value for user.id8
     *
     * @mbggenerated
     */
    public void setId8(Float id8) {
        this.id8 = id8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id9
     *
     * @return the value of user.id9
     *
     * @mbggenerated
     */
    public String getId9() {
        return id9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id9
     *
     * @param id9 the value for user.id9
     *
     * @mbggenerated
     */
    public void setId9(String id9) {
        this.id9 = id9 == null ? null : id9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id10
     *
     * @return the value of user.id10
     *
     * @mbggenerated
     */
    public String getId10() {
        return id10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id10
     *
     * @param id10 the value for user.id10
     *
     * @mbggenerated
     */
    public void setId10(String id10) {
        this.id10 = id10 == null ? null : id10.trim();
    }
}